# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170113_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
